# ==========================================
# ALERTMANAGER CONFIGURATION FOR COMICCOMP
# Handles alert routing and notifications
# ==========================================

global:
  # The smarthost and SMTP sender used for mail notifications
  smtp_smarthost: 'smtp.resend.com:587'
  smtp_from: 'alerts@comicogs.com'
  smtp_auth_username: 'resend'
  smtp_auth_password: 'YOUR_RESEND_API_KEY'
  smtp_require_tls: true

  # The root route on which each incoming alert enters
  # Used for grouping and routing alerts
  resolve_timeout: 5m

# The directory from which notification templates are read
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each incoming alert enters
route:
  # The labels by which incoming alerts are grouped together
  group_by: ['alertname', 'service']
  
  # How long to initially wait to send a notification for a group of alerts
  group_wait: 30s
  
  # How long to wait before sending notification about new alerts that are added to a group
  group_interval: 5m
  
  # How long to wait before sending a notification again if it has already been sent
  repeat_interval: 12h
  
  # Default receiver for all alerts
  receiver: 'default'
  
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 5m
      
    # Security alerts - immediate notification
    - match:
        service: security
      receiver: 'security-team'
      group_wait: 0s
      group_interval: 30s
      repeat_interval: 1h
      
    # Database alerts - DBA team
    - match:
        service: database
      receiver: 'database-team'
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 30m
      
    # Payment alerts - business team
    - match:
        service: payments
      receiver: 'business-team'
      group_wait: 30s
      group_interval: 2m
      repeat_interval: 15m
      
    # Business metrics - info only during business hours
    - match:
        service: business
      receiver: 'business-metrics'
      group_wait: 10m
      group_interval: 1h
      repeat_interval: 6h
      
    # Warning alerts - standard handling
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 2m
      group_interval: 10m
      repeat_interval: 2h

# Inhibition rules allow to mute a set of alerts given that another alert is firing
inhibit_rules:
  # Mute warning alerts if critical alert for same service is firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'alertname']
    
  # Mute individual instance alerts if service is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match_re:
      alertname: '(HighResponseTime|HighErrorRate)'
    equal: ['service']

receivers:
  # Default receiver
  - name: 'default'
    email_configs:
      - to: 'devops@comicogs.com'
        subject: '[ComicComp] {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
        headers:
          X-Priority: 'Normal'

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: 'devops@comicogs.com,cto@comicogs.com'
        subject: '[CRITICAL] ComicComp Alert - {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ if .EndsAt }}Ended: {{ .EndsAt.Format "2006-01-02 15:04:05 UTC" }}{{ end }}
          
          Runbook: https://docs.comicogs.com/runbooks/{{ .Labels.alertname | toLower }}
          {{ end }}
        headers:
          X-Priority: 'High'
    
    # Slack notification for critical alerts
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-critical'
        color: 'danger'
        title: '🚨 Critical Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* {{ .Labels.service }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        actions:
          - type: button
            text: 'View Grafana Dashboard'
            url: 'https://monitoring.comicogs.com/d/overview'
          - type: button
            text: 'View Logs'
            url: 'https://logs.comicogs.com'
    
    # PagerDuty for critical alerts (if configured)
    # pagerduty_configs:
    #   - service_key: 'YOUR_PAGERDUTY_SERVICE_KEY'
    #     description: '{{ .GroupLabels.alertname }}: {{ .Annotations.summary }}'

  # Security team alerts
  - name: 'security-team'
    email_configs:
      - to: 'security@comicogs.com,devops@comicogs.com'
        subject: '[SECURITY] ComicComp Security Alert - {{ .GroupLabels.alertname }}'
        body: |
          🔒 SECURITY ALERT 🔒
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
          
          Please investigate immediately and follow security incident procedures.
        headers:
          X-Priority: 'High'
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#security-alerts'
        color: 'warning'
        title: '🔒 Security Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Database team alerts
  - name: 'database-team'
    email_configs:
      - to: 'dba@comicogs.com,devops@comicogs.com'
        subject: '[DATABASE] ComicComp DB Alert - {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          {{ end }}
        headers:
          X-Priority: 'Normal'

  # Business team alerts
  - name: 'business-team'
    email_configs:
      - to: 'business@comicogs.com'
        subject: '[BUSINESS] ComicComp Business Alert - {{ .GroupLabels.alertname }}'
        body: |
          💼 BUSINESS ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
        headers:
          X-Priority: 'Normal'
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#business-alerts'
        color: 'warning'
        title: '💼 Business Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Business metrics - info notifications
  - name: 'business-metrics'
    email_configs:
      - to: 'analytics@comicogs.com'
        subject: '[INFO] ComicComp Metrics - {{ .GroupLabels.alertname }}'
        body: |
          📊 BUSINESS METRICS NOTIFICATION
          
          {{ range .Alerts }}
          Metric: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          {{ end }}
        headers:
          X-Priority: 'Low'

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: 'devops@comicogs.com'
        subject: '[WARNING] ComicComp Alert - {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          {{ end }}
        headers:
          X-Priority: 'Normal'
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-warning'
        color: 'warning'
        title: '⚠️ Warning Alert - {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Service:* {{ .Labels.service }}
          *Alert:* {{ .Annotations.summary }}
          {{ end }}